//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5472
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyGate_Global_3D_Secure_Enterprise_Example.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://enterprise.mygateglobal.com/5x0x0/ePayService.cfc")]
        public string MyGate_Global_3D_Secure_Enterprise_Example_wsCCPayments_ePayService {
            get {
                return ((string)(this["MyGate_Global_3D_Secure_Enterprise_Example_wsCCPayments_ePayService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://3dsecure.mygateglobal.com/3DSecure.cfc")]
        public string MyGate_Global_3D_Secure_Enterprise_Example_ws3DSecure_3DSecure1 {
            get {
                return ((string)(this["MyGate_Global_3D_Secure_Enterprise_Example_ws3DSecure_3DSecure1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://dev-3dsecure.mygateglobal.com/3DSecure.cfc")]
        public string MyGate_Global_3D_Secure_Enterprise_Example_Dev_ws3DSecure_3DSecure1 {
            get {
                return ((string)(this["MyGate_Global_3D_Secure_Enterprise_Example_Dev_ws3DSecure_3DSecure1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://dev-enterprise.mygateglobal.com/5x0x0/ePayService.cfc")]
        public string MyGate_Global_3D_Secure_Enterprise_Example_wsCCPayments_sandbox_ePayService {
            get {
                return ((string)(this["MyGate_Global_3D_Secure_Enterprise_Example_wsCCPayments_sandbox_ePayService"]));
            }
        }
    }
}
