//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyGate_Global_3D_Secure_Enterprise_Example_3dsecure_mygateglobal_com
{
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "3.2.1.6466")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="3DSecure.cfcSoapBinding", Namespace="https://3dsecure.mygateglobal.com/3DSecure.cfc")]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(QueryBean))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(CFCInvocationException))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(Map))]
    public partial class Item3DSecure1 : System.Web.Services.Protocols.SoapHttpClientProtocol
    {
        
        /// <remarks/>
        public Item3DSecure1()
        {
            this.Url = "https://3dsecure.mygateglobal.com/3DSecure.cfc";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="https://3dsecure.mygateglobal.com/3DSecure.cfc", ResponseNamespace="https://3dsecure.mygateglobal.com/3DSecure.cfc")]
        [return: System.Xml.Serialization.SoapElementAttribute("lookupReturn")]
        public object[] lookup(string MerchantID, string ApplicationID, double Mode, string PAN, string PANExpr, string PurchaseAmount, string UserAgent, string BrowserHeader, string OrderNumber, string OrderDesc, string Recurring, string RecurringFrequency, string RecurringEnd, string Installment)
        {
            object[] results = this.Invoke("lookup", new object[] {
                        MerchantID,
                        ApplicationID,
                        Mode,
                        PAN,
                        PANExpr,
                        PurchaseAmount,
                        UserAgent,
                        BrowserHeader,
                        OrderNumber,
                        OrderDesc,
                        Recurring,
                        RecurringFrequency,
                        RecurringEnd,
                        Installment});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginlookup(
                    string MerchantID, 
                    string ApplicationID, 
                    double Mode, 
                    string PAN, 
                    string PANExpr, 
                    string PurchaseAmount, 
                    string UserAgent, 
                    string BrowserHeader, 
                    string OrderNumber, 
                    string OrderDesc, 
                    string Recurring, 
                    string RecurringFrequency, 
                    string RecurringEnd, 
                    string Installment, 
                    System.AsyncCallback callback, 
                    object asyncState)
        {
            return this.BeginInvoke("lookup", new object[] {
                        MerchantID,
                        ApplicationID,
                        Mode,
                        PAN,
                        PANExpr,
                        PurchaseAmount,
                        UserAgent,
                        BrowserHeader,
                        OrderNumber,
                        OrderDesc,
                        Recurring,
                        RecurringFrequency,
                        RecurringEnd,
                        Installment}, callback, asyncState);
        }
        
        /// <remarks/>
        public object[] Endlookup(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="https://3dsecure.mygateglobal.com/3DSecure.cfc", ResponseNamespace="https://3dsecure.mygateglobal.com/3DSecure.cfc")]
        [return: System.Xml.Serialization.SoapElementAttribute("authenticateReturn")]
        public object[] authenticate(string TransactionIndex, string PAResPayload)
        {
            object[] results = this.Invoke("authenticate", new object[] {
                        TransactionIndex,
                        PAResPayload});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginauthenticate(string TransactionIndex, string PAResPayload, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("authenticate", new object[] {
                        TransactionIndex,
                        PAResPayload}, callback, asyncState);
        }
        
        /// <remarks/>
        public object[] Endauthenticate(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="https://3dsecure.mygateglobal.com/3DSecure.cfc", ResponseNamespace="https://3dsecure.mygateglobal.com/3DSecure.cfc")]
        [return: System.Xml.Serialization.SoapElementAttribute("tokenLookupReturn")]
        public object[] tokenLookup(string MerchantID, string ApplicationID, double Mode, string ClientToken, string PurchaseAmount, string UserAgent, string BrowserHeader, string OrderNumber, string OrderDesc, string Recurring, string RecurringFrequency, string RecurringEnd, string Installment)
        {
            object[] results = this.Invoke("tokenLookup", new object[] {
                        MerchantID,
                        ApplicationID,
                        Mode,
                        ClientToken,
                        PurchaseAmount,
                        UserAgent,
                        BrowserHeader,
                        OrderNumber,
                        OrderDesc,
                        Recurring,
                        RecurringFrequency,
                        RecurringEnd,
                        Installment});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegintokenLookup(string MerchantID, string ApplicationID, double Mode, string ClientToken, string PurchaseAmount, string UserAgent, string BrowserHeader, string OrderNumber, string OrderDesc, string Recurring, string RecurringFrequency, string RecurringEnd, string Installment, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("tokenLookup", new object[] {
                        MerchantID,
                        ApplicationID,
                        Mode,
                        ClientToken,
                        PurchaseAmount,
                        UserAgent,
                        BrowserHeader,
                        OrderNumber,
                        OrderDesc,
                        Recurring,
                        RecurringFrequency,
                        RecurringEnd,
                        Installment}, callback, asyncState);
        }
        
        /// <remarks/>
        public object[] EndtokenLookup(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((object[])(results[0]));
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "3.2.1.6466")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://rpc.xml.coldfusion")]
    public partial class QueryBean
    {
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string[] columnList;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public object[] data;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "3.2.1.6466")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://rpc.xml.coldfusion")]
    public partial class CFCInvocationException
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "3.2.1.6466")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://xml.apache.org/xml-soap")]
    public partial class Map
    {
        
        /// <remarks/>
        public mapItem[] item;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "3.2.1.6466")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://xml.apache.org/xml-soap")]
    public partial class mapItem
    {
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public object key;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public object value;
    }
}
